SELECT DETALLE_FACTURA.id_detalle, PRODUCTO.nombre,FACTURA.fecha as mes
FROM DETALLE_FACTURA
JOIN PRODUCTO ON DETALLE_FACTURA.id_producto = PRODUCTO.id_producto
JOIN FACTURA ON DETALLE_FACTURA.id_factura = FACTURA.id_factura
WHERE mes BETWEEN "2025-01-02" AND "2025-01-31"
